# Generated by Django 5.1.6 on 2025-04-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_created_at_post_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category1',
            new_name='category',
        ),
    ]
