# Generated by Django 5.1.6 on 2025-06-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_src',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
