# Generated by Django 5.1.6 on 2025-06-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_img_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_src',
            new_name='img_url',
        ),
    ]
