# Generated by Django 5.1.6 on 2025-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_img_src_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(max_length=200, null=True, upload_to='posts/images'),
        ),
    ]
